apiVersion: v1
kind: Service
metadata:
  namespace: frontendrb
  name: fe-service-rb
spec:
  type: LoadBalancer
  selector:
    app: resumebuilder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
