apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200  # Exposing port 4200 to the service
      targetPort: 4200  # Port the frontend container is listening on
  type: NodePort  # Use NodePort to expose the frontend locally
